### ISSUE TITLE
Crash on start when using sqlite due to missing ',' character

### ISSUE THREAD

**Issue by bagage** [ChazDazzle/fpdb-chaz#1]
In your commit 109bb94e, you removed a comma which is needed to generate the database at SQL.py:351. Adding it back and everything's fine.

**Comment by ChazDazzle** [comment]
Fixed in 109bcc5

**Comment by bagage** [comment]
Dude, is there a way to reach you directly? I'd like to code some thinks on fpdb for myself, but beeing able to reach the main dev directly would be powerful :) I don't think the IRC chan or the mailist list is appropriated for my thoughts since it's pretty minors things (like tourney graph viewer isn't usable for non-USD ppl because 'tourneyGraph' request use a currency condition but we can't set it to our desired one!). BTW i'm on IRC (cqnqrd).

**Comment by ChazDazzle** [comment]
Yeah, email me at chaz@pokeit.co. I'm not on IRC much, but we're always
looking to accept patches fixing GUI bugs and such. Thanks!
