### ISSUE TITLE
Does not get the values of the won in the tournaments

### ISSUE THREAD

**Issue by Geral-Ortiz** [ChazDazzle/fpdb-chaz#19]
i updated the fpdb to solve the problem with the bounty builders in pokerstars, and now dont show this values in tournament stats "Won - %ROI - $/tour"

![seleccion_016](https://cloud.githubusercontent.com/assets/24262082/21739366/a53f35d2-d46f-11e6-9540-20958f85da34.png)
![seleccion_017](https://cloud.githubusercontent.com/assets/24262082/21739369/a7dc72c8-d46f-11e6-84b7-81127a79c317.png)

**Comment by Geral-Ortiz** [comment]
i use PostgreSQL because in linux not work the program with Mysql

**Comment by ChazDazzle** [comment]
OK i'll take a look

**Comment by Geral-Ortiz** [comment]
Hello, I realized that if you play MTT or SNG without the HUD on, and then register them with the bulk import, it does not record when you win, maybe it will be useful. You could tell me which part of the program is responsible for collecting this data, could review and test

**Comment by ChazDazzle** [comment]
Have you tried importing tournament summaries via bulk import too?

**Comment by Geral-Ortiz** [comment]
Correct, and when I do, I check in tourament stats does not add tournament data, but, if I play tournaments with the HUD autoimport activated if I add them, no problem.
Do not add them when I add them by bulk import

**Comment by ChazDazzle** [comment]
Just started with a fresh database and 0.41.0-rc8 and was able to import all the files in the tournament summary folder. Can you send your log files to me at support@pokeit.co? Should be in C:\Users\[USER NAME]\AppData\Roaming\fpdb\log
